import Foundation

/// Every bundled asset — `SKILL.md` today, anything else we ship tomorrow — is looked up through
/// here rather than through `Bundle.module`.
///
/// `Bundle.module` is generated by SwiftPM and tries exactly two locations: the *bundle root* of
/// `Bundle.main`, and an absolute `.build/…` path baked in at compile time. Neither survives
/// shipping. For an app, `Bundle.main.bundleURL` is `Meetings.app` itself, and `codesign` refuses to
/// seal loose content sitting next to `Contents/` — so the resource bundle has to live in
/// `Contents/Resources/`, which `Bundle.module` never looks at. It then silently falls through to the
/// baked-in `.build` path, which exists on the machine that built the app and nowhere else. The app
/// therefore works on this Mac and traps with `could not load resource bundle` the moment it is
/// moved or `.build` is cleaned.
public enum BundleResources {
    /// SwiftPM names a target's resource bundle `<Package>_<Target>.bundle`.
    public static let bundleName = "Meetings_MeetingsCore.bundle"

    /// `.copy("Resources")` copies the *directory*, so assets keep their `Resources/` prefix inside
    /// the bundle instead of landing at its root.
    private static let subdirectory = "Resources"

    /// The resolution rule, as a pure function so both branches are testable without an assembled
    /// `.app`. Inside the app `mainResourceURL` is `Meetings.app/Contents/Resources`; for the CLI and
    /// under `swift test` there is no such nested bundle and we fall back to SwiftPM's own accessor,
    /// whose `.build` path is correct in exactly that case.
    public static func locate(mainResourceURL: URL?) -> Bundle {
        if let mainResourceURL,
           let nested = Bundle(url: mainResourceURL.appendingPathComponent(bundleName)) {
            return nested
        }
        return .module
    }

    public static let bundle: Bundle = locate(mainResourceURL: Bundle.main.resourceURL)

    public static func url(forResource name: String, withExtension ext: String, in bundle: Bundle = bundle) -> URL? {
        bundle.url(forResource: name, withExtension: ext, subdirectory: subdirectory)
    }

    /// The agent skill `meetings skill install` writes to `~/.claude/skills/meetings/`.
    public static func skillMarkdown(in bundle: Bundle = bundle) throws -> String {
        guard let url = url(forResource: "SKILL", withExtension: "md", in: bundle) else {
            throw CocoaError(.fileNoSuchFile, userInfo: [
                NSFilePathErrorKey: bundle.bundlePath + "/\(subdirectory)/SKILL.md"
            ])
        }
        return try String(contentsOf: url, encoding: .utf8)
    }
}
