import Foundation

/// Every bundled asset — `SKILL.md` today, anything else we ship tomorrow — is looked up through
/// here rather than through `Bundle.module`.
///
/// `Bundle.module` is generated by SwiftPM and tries exactly two locations: the *bundle root* of
/// `Bundle.main`, and an absolute `.build/…` path baked in at compile time. Neither survives
/// shipping. For an app, `Bundle.main.bundleURL` is `Meetings.app` itself, and `codesign` refuses to
/// seal loose content sitting next to `Contents/` — so the resource bundle has to live in
/// `Contents/Resources/`, which `Bundle.module` never looks at. It then silently falls through to the
/// baked-in `.build` path, which exists on the machine that built the app and nowhere else. The app
/// therefore works on this Mac and traps with `could not load resource bundle` the moment it is
/// moved or `.build` is cleaned.
public enum BundleResources {
    /// SwiftPM names a target's resource bundle `<Package>_<Target>.bundle`.
    public static let bundleName = "Meetings_MeetingsCore.bundle"

    /// `.copy("Resources")` copies the *directory*, so assets keep their `Resources/` prefix inside
    /// the bundle instead of landing at its root.
    private static let subdirectory = "Resources"

    /// The resolution rule, as a pure function so every branch is testable without an assembled
    /// `.app`. Three candidates, in order:
    ///
    /// 1. **Inside the app.** `mainResourceURL` is `Meetings.app/Contents/Resources`, and the bundle
    ///    sits directly in it.
    /// 2. **The shipped CLI**, which is the branch this used to get wrong. `meetings` lives at
    ///    `Meetings.app/Contents/Helpers/meetings`, so its resource bundle is one directory up and
    ///    across, in `Contents/Resources`. The executable path is resolved through symlinks first,
    ///    because the installer links the CLI onto `PATH` — and for a bare executable
    ///    `Bundle.main.resourceURL` is the directory the binary was *invoked* from, which for a
    ///    symlink is `~/.local/bin`. Candidate 1 therefore misses, and before this candidate existed
    ///    the lookup fell through to candidate 3.
    /// 3. **A build tree or `swift test`**, where SwiftPM's accessor is right and its baked `.build`
    ///    path really is where the bundle is.
    ///
    /// What made this expensive to find: candidate 3 succeeds on the machine that compiled the
    /// binary, so every local run and every CI run passed while every published release shipped a CLI
    /// that trapped on `could not load resource bundle`. Only a Mac that did not build it can tell.
    public static func locate(mainResourceURL: URL?, executableURL: URL? = nil) -> Bundle {
        if let mainResourceURL,
           let nested = Bundle(url: mainResourceURL.appendingPathComponent(bundleName)) {
            return nested
        }
        if let executableURL {
            let contents = executableURL
                .resolvingSymlinksInPath()
                .deletingLastPathComponent()   // Contents/Helpers
                .deletingLastPathComponent()   // Contents
            let sibling = contents
                .appendingPathComponent("Resources")
                .appendingPathComponent(bundleName)
            if let nested = Bundle(url: sibling) {
                return nested
            }
        }
        return .module
    }

    public static let bundle: Bundle = locate(
        mainResourceURL: Bundle.main.resourceURL,
        executableURL: Bundle.main.executableURL
    )

    public static func url(forResource name: String, withExtension ext: String, in bundle: Bundle = bundle) -> URL? {
        bundle.url(forResource: name, withExtension: ext, subdirectory: subdirectory)
    }

    /// The agent skill `meetings skill install` writes to `~/.claude/skills/meetings/`.
    public static func skillMarkdown(in bundle: Bundle = bundle) throws -> String {
        guard let url = url(forResource: "SKILL", withExtension: "md", in: bundle) else {
            throw CocoaError(.fileNoSuchFile, userInfo: [
                NSFilePathErrorKey: bundle.bundlePath + "/\(subdirectory)/SKILL.md"
            ])
        }
        return try String(contentsOf: url, encoding: .utf8)
    }
}
